services:
  redis:
    image: redis
    container_name: redis-compose-server
    networks:
      - redis-new-network
    ports:
      - 6379:6379

  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-compose-container
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - redis-new-network

networks:
  redis-new-network:
    driver: bridge